version: "2"
services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
  worker:
    build: ./
    volumes:
      - ./src:/opt/app
    command: python -m celery -A server.celery_app worker
    environment:
      REDIS_HOST: redis
      C_FORCE_ROOT: 'true'
      REDIS_PORT: 6379
      MAIL_SERVER: 'smtp.gmail.com'
      MAIL_PORT: 465
      MAIL_USE_SSL: 'True'
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      MAIL_DEFAULT_SENDER: ''
    links:
      - redis:redis
  mailer:
    build: ./
    command: python server.py
    volumes:
      - ./src:/opt/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_SERVER: 'smtp.gmail.com'
      MAIL_PORT: 465
      MAIL_USE_SSL: 'True'
      MAIL_USERNAME: ''
      MAIL_PASSWORD: ''
      MAIL_DEFAULT_SENDER: ''
    ports:
      - "3000:3000"
