import os

#REDIS CONFIG
CELERY_BROKER_URL='redis://127.0.0.1:6379'
CELERY_BACKEND='redis://127.0.0.1:6379'

# MAILER CONFIG
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT=465
MAIL_USE_SSL=True
MAIL_USERNAME=''
MAIL_PASSWORD=''
MAIL_DEFAULT_SENDER=''
